version: '2'
services:
  web:
    restart: always
    build: ./www
    ports:
      - "8000"
    volumes:
      - ./www:/usr/src/app
    environment:
      - PATH=/usr/src/app/:$PATH
      - PYTHONPATH=/usr/src/app/
      - DJANGO_SETTINGS_MODULE=unicooo.settings.production
    command: bash -c "python manage.py makemigrations && python manage.py migrate && /usr/local/bin/gunicorn unicooo.wsgi:application -w 3 --timeout 200 -k gevent -b :8000"
    links:
      - redis:redis
  nginx:
    restart: always
    build: ./nginx_pro/
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ~/www:/www
     - ./nginx/sites-enabled/:/etc/nginx/conf.d
     - ./nginx/settings/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - web
    links:
      - web:web
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
    redisdata:

