version: '2'
services:
  db:
   image: mysql
   restart: always
   volumes:
     - mysqldata:/var/lib/mysql
   ports:
     - "3306:3306"
   env_file: env/mysql.env
  web:
    restart: always
    build: ./www
    ports:
      - "8000"
    volumes:
      - ./www:/usr/src/app
    command: bash -c "export DJANGO_SETTINGS_MODULE='unicooo.settings.local' && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && /usr/local/bin/gunicorn unicooo.wsgi:application -w 2 -b :8000 --reload"
    depends_on:
      - db
    links:
      - redis:redis
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
    mysqldata:
    redisdata:
