version: '2'
services:
  db:
   image: mysql
   restart: always
   volumes:
     - mysqldata:/var/lib/mysql
     - ./env/:/etc/mysql/conf.d
   ports:
     - "3306:3306"
   env_file: env/mysql.env
  web:
    restart: always
    build: ./www
    ports:
      - "8000"
      - "8081:8081"
    environment:
      - PATH=/usr/src/app/:$PATH
      - PYTHONPATH=/usr/src/app/
      - DJANGO_SETTINGS_MODULE=unicooo.settings.local
    volumes:
      - ./www:/usr/src/app
    command: /bin/sh -c "python manage.py migrate && /usr/local/bin/gunicorn unicooo.wsgi:application -w 3 --timeout 200 -k gevent -b 0.0.0.0:8000 --reload"
    links:
      - redis:redis
  nginx_d:
    restart: always
    build: ./nginx_test/
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - ./www/public/:/var/public/
        - ./nginx_test/sites-enabled/:/etc/nginx/conf.d
        - ./nginx_test/settings/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - web
    links:
      - web:web
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
    mysqldata:
    redisdata:
