# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_ident',
            field=models.CharField(max_length=50),
        ),
    ]
