# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20160308_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_ident',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='act',
            name='act_type',
            field=models.IntegerField(choices=[(0, 'For yourself'), (1, 'For a group'), (2, 'For public')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='act',
            unique_together=set([('user', 'act_ident')]),
        ),
    ]
