# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20160329_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_ident',
            field=models.IntegerField(default=1000),
        ),
    ]
