# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20160329_0745'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='act',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='act',
            index_together=set([]),
        ),
    ]
