# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_avatar',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
