# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20160308_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_gender',
            field=models.IntegerField(choices=[(0, 'SECRET'), (1, 'MALE'), (2, 'FEMALE')], default=0),
        ),
    ]
