# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20160308_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_point',
            field=models.IntegerField(default=50),
        ),
    ]
