# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, max_length=30)),
                ('post_content', models.CharField(max_length=140)),
                ('post_thumb_url', models.CharField(max_length=255)),
                ('post_thumb_width', models.IntegerField()),
                ('post_thumb_height', models.IntegerField()),
                ('post_mime_types', models.IntegerField(choices=[(0, 'IMAGE'), (1, 'AUDIO'), (2, 'VIDEO')], default=0)),
                ('nsfw', models.IntegerField()),
                ('post_create_time', models.DateTimeField(auto_now=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_act', to='activities.Act')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
