# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_thumb_url',
            field=models.CharField(max_length=512),
        ),
    ]
