# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170612_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
