# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-21 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20170612_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['-act_create_time']},
        ),
    ]
