# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-22 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20170621_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_content',
            field=models.CharField(max_length=255),
        ),
    ]
