# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20160223_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_ident',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='act_url',
            field=models.CharField(max_length=255),
        ),
    ]
