# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20170622_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_title',
            field=models.CharField(max_length=50),
        ),
    ]
