# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_name_vali',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
