# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-13 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_myuser_user_name_vali'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_name_vali',
        ),
    ]
