# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20151127_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_gender',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'MALE'), (2, 'FEMALE')], default=0),
        ),
    ]
