# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20160229_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_avatar',
            field=models.CharField(max_length=255),
        ),
    ]
